version: '2.1'
services:
  app:
    build: docker/images/php
    links:
      - localstack
    volumes:
      - ./app:/app:cached
      - ./logs:/logs
    working_dir: /app

  localstack:
    image: localstack/localstack:0.8.2
    ports:
      #- 4567-4582:4567-4582
      - 8086:8080
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # - ${TMP_DIR:-/tmp/localstack}:/tmp/localstack:delegated
      - /var/run/docker.sock:/var/run/docker.sock:cached
